run:
  command: all
  datadir: ./data
  siteid: <REPLACE_ME>
  sitedir: <REPLACE_ME>
  firstyear: <REPLACE_ME>
  lastyear: <REPLACE_ME>
  perc:
  prod:
  logfile: oneflux.log
  force_py: false
  mcr: <REPLACE_ME>/MATLAB_Runtime/v94
  ts: oneflux.tools.pipeline:NOW_TS
  recint: hh
  versionp: oneflux:VERSION_PROCESSING
  versiond: oneflux:VERSION_METADATA
  era_fy: oneflux.pipeline.common:ERA_FIRST_YEAR
  era_ly: oneflux.pipeline.common:ERA_LAST_YEAR
  configfile:

steps:
    qc_auto_execute: true
    ustar_mp_execute: true
    ustar_cp_execute: true
    meteo_proc_execute: true
    nee_proc_execute: true
    energy_proc_execute: true
    nee_partition_nt_execute: true
    nee_partition_dt_execute: true
    prepare_ure_execute: true
    ure_execute: true
    fluxnet2015_execute: true
    fluxnet2015_site_plots: true
    simulation: false

01_qc_visual:
  dummy-step-1: dummy_step_1_test_string

07_meteo_proc:
  dummy-step-7: dummy_step_7_test_string
  mds-params:
    TA:
      tofill: "TA"
      #oor_min: -50
      #oor_max: 50
      driver1: "SW_IN"
      driver2a: "TA"
      driver2b: "VPD"
      tdriver1_min: 20
      tdriver1_max: 50
      tdriver2a_min: 2.5
      tdriver2a_max: 5
      tdriver2b_min: 5
      tdriver2b_max: 10
      odriver1_min: 0
      odriver1_max: 1000
      odriver2a_min: 0
      odriver2a_max: 100
      odriver2b_min: 0
      odriver2b_max: 100
      
    SW_IN:
      tofill: "SW_IN"
      #oor_min: -5
      #oor_max: 2000
      driver1: "SW_IN"
      driver2a: "TA"
      driver2b: "VPD"
      tdriver1_min: 20
      tdriver1_max: 50
      tdriver2a_min: 2.5
      tdriver2a_max: 5
      tdriver2b_min: 5
      tdriver2b_max: 10
      odriver1_min: 0
      odriver1_max: 1000
      odriver2a_min: -50
      odriver2a_max: 50
      odriver2b_min: 0
      odriver2b_max: 100

      
    LW_IN:
      tofill: "LW_IN"
      #oor_min: -5
      #oor_max: 500
      driver1: "SW_IN"
      driver2a: "TA"
      driver2b: "VPD"
      tdriver1_min: 20
      tdriver1_max: 50
      tdriver2a_min: 2.5
      tdriver2a_max: 5
      tdriver2b_min: 5
      tdriver2b_max: 10
      odriver1_min: -5
      odriver1_max: 2000
      odriver2a_min: -50
      odriver2a_max: 50
      odriver2b_min: 0
      odriver2b_max: 100
       
    CO2:
      tofill: "CO2"
      #oor_min: 0
      #oor_max: 100
      driver1: "SW_IN"
      driver2a: "TA"
      driver2b: "VPD"
      tdriver1_min: 20
      tdriver1_max: 50
      tdriver2a_min: 2.5
      tdriver2a_max: 5
      tdriver2b_min: 5
      tdriver2b_max: 10
      odriver1_min: -5
      odriver1_max: 2000
      odriver2a_min: -50
      odriver2a_max: 50
      odriver2b_min: 0
      odriver2b_max: 100

    VPD:
      tofill: "VPD"
      #oor_min: 0
      #oor_max: 100
      driver1: "SW_IN"
      driver2a: "TA"
      driver2b: "VPD"
      tdriver1_min: 20
      tdriver1_max: 50
      tdriver2a_min: 2.5
      tdriver2a_max: 5
      tdriver2b_min: 5
      tdriver2b_max: 10
      odriver1_min: -5
      odriver1_max: 2000
      odriver2a_min: -50
      odriver2a_max: 50
      odriver2b_min: 0
      odriver2b_max: 100
     
    TS:
      tofill: "TS"
      #oor_min: -50
      #oor_max: 50
      driver1: "SW_IN"
      driver2a: "TA"
      driver2b: "VPD"
      tdriver1_min: 20
      tdriver1_max: 50
      tdriver2a_min: 2.5
      tdriver2a_max: 5
      tdriver2b_min: 5
      tdriver2b_max: 10
      odriver1_min: -5
      odriver1_max: 2000
      odriver2a_min: -50
      odriver2a_max: 50
      odriver2b_min: 0
      odriver2b_max: 100
   
    SWC:
      tofill: "SWC"
      #oor_min: 0
      #oor_max: 100
      driver1: "SW_IN"
      driver2a: "TA"
      driver2b: "VPD"
      tdriver1_min: 20
      tdriver1_max: 50
      tdriver2a_min: 2.5
      tdriver2a_max: 5
      tdriver2b_min: 5
      tdriver2b_max: 10
      odriver1_min: -5
      odriver1_max: 2000
      odriver2a_min: -50
      odriver2a_max: 50
      odriver2b_min: 0
      odriver2b_max: 100

      